config/routes.rb
Rails.application.routes.draw do

  get "registered_applications/index"
  get "registered_applications/show"
  get "registered_applications/new"
  get "registered_applications/edit"
  get "users/show"
  get "users/index"

  devise_for :users
  resources :users

  resources :registered_applications do
    resources :users
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  get 'welcome/index'
  get 'welcome/about'
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,:confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :registered_applications       
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token, :authenticate_user!
  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    @registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])

    if @registered_application.nil?
      puts "registered app is nil"
      render json: "Unregistered application.", status: :unprocessable_entity
    else
      @event = @registered_application.events.new(event_params)
      if @event.save
        render json: @event, status: :created
      else
        puts "an error occurred saving the event"
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end
  end

  def preflight
    head 200
  end


  private
  def event_params
    params.require(:event).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:about]

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
 before_action :authenticate_user!

  def index
     @registered_applications = RegisteredApplication.all
  end

  def show
    @registered_applications = RegisteredApplication.all
    @user = current_user
    @registered_application = @user.registered_applications

    if @registered_application.first.nil?
      redirect_to registered_applications_new_path, notice: "You must register an application first."
    else
      @events = @registered_application.first.events.group_by(&:name)
    end
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(app_params)
    @registered_application.user = current_user

    if @registered_application.save
       redirect_to @registered_application, notice: "The application was registered successfully."
    else
      flash.now[:alert] = "Error registering application. Please try again."
      render :new
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    @registered_application.assign_attributes(app_params)

    if @registered_application.save
       redirect_to @registered_application, notice: "The application was updated successfully."
    else
      flash.now[:alert] = "Error editing application. Please try again."
      render :edit
    end

  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    if @registered_application.destroy
     flash[:notice] = "\"#{@registered_application.name}\" was deleted successfully."
     redirect_to registered_applications_show_path
    else
     flash.now[:alert] = "There was an error deleting the application."
     render :show
    end
  end

  private
  def app_params
    params.require(:registered_application).permit(:name, :url, :user_id, :id)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @registered_applications = RegisteredApplication.all
    @users = User.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
      </ul>
      <div class="jumbotron">
          <h2 class="cover-heading">Blocmetrics</h2>
          <h3 class="cover-subheading">A analytics service to track events on your website.</h3>
      </div>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

    <% if user_signed_in? %>
      Signed in as: <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
       <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
       <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
   <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/registered_applications/_form.html.erb
<%= form_for @registered_application do |f| %>
 <div class="form-group">
   <%= f.label :name %>
   <%= f.text_field :name, class: 'form-control', placeholder: "Enter application name" %>
 </div>

 <div class="form-group">
   <%= f.label :url %>
   <%= f.text_area :url, rows: 2, class: 'form-control', placeholder: "Enter application url" %>
 </div>

 <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
 </div>
 <% end %>

app/views/registered_applications/edit.html.erb
<h1>Edit Application</h1>
<div class="col-md-8">
   <%= render partial: 'form', locals: { registered_application: @registered_application } %>
</div>

app/views/registered_applications/index.html.erb
<div class="row">
  <div class="col-md-8">
   <h1>Registered Applications</h1>
    <div class="media">
       <div class="media-body">
         <h4 class="media-heading">
          <% @registered_applications.each do |app| %>
              <h4>Name: <%= app.name %>  Url: <%= app.url %></h4>
          <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
     <div class="col-md-8">
      <%= link_to "Create New", new_registered_application_path(@registered_application), class: 'btn btn-success' %>
     </div>
   </div>
 </div>

app/views/registered_applications/new.html.erb
<div class="col-md-8">
   <%= render partial: 'form', locals: { registered_application: @registered_application } %>
</div>

app/views/registered_applications/show.html.erb
<div class="row">
  <div class="col-md-8">
  <h2> Your applications </h2>
  <div class="media">
   <div class="media-body">
     <h4 class="media-heading">
     <% @registered_applications.each do |app| %>
     <% if app.user_id == current_user.id %>
      <h4>Name: <%= app.name %> | url: <%= app.url %></h4>
      <h4>Events Summary</h4>
      <%= pie_chart app.events.group(:name).count, download: true, legend: "right" %>
      <%= line_chart app.events.group_by_day(:created_at).count, xtitle: "Date", ytitle: "Number of events", download: true %>
      <h4>Manage <%= app.name %> </h4>
      <%= link_to "Edit", edit_registered_application_path(app), class: 'btn btn-success' %>
      <%= link_to "Delete", app, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this application?' } %>
     <% end %>
     <% end %>
    </div>
   </div>
  </div>
</div>

<div class="row">
     <div class="col-md-8">
       <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
      <%= link_to "Create New", new_registered_application_path(@registered_application), class: 'btn btn-success' %>
     </div>
   </div>
 </div>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/about.html.erb
<div class="row">
 <div class="col-md-8">
    <h2>Key features: </h2>
    <ul>
     <li>Server-side API that captures and saves those events to a database</li>
     <li>Rails application that displays the captured event data for a user</li>
     <li>Client-side JavaScript snippet that allows users to track events on their website</li>
    </ul>
 </div>
</div>
<div class="row">
 <div class="col-md-8">
   <h3>Getting Started</h3>
    <p>Paste the JavaScript code snippet below in your application or pages within your website to track specific events.</p>
  <p>var blocmetrics = {};
  <br/>
    blocmetrics.report = function(eventName){
  <br/>
      var event = { event: { name: eventName }};
  <br/>
      var request = new XMLHttpRequest();
  <br/>
      request.open("POST","https://stark-forest-69447.herokuapp.com/api/events", true);
  <br/>
      request.setRequestHeader('Content-Type', 'application/json');
  <br/>
      request.send(JSON.stringify(event));
  <br/>
      };
  <br/>
        </p>
<h3>Usage</h3>
Call blocmetrics.report('eventName') to the relevant views, customizing for the event you wish to track, e.g.:
<br/>
window.onload = function() {
  <br/>
  blocmetrics.report('eventName');
  <br/>
}

<h3>Sign up for a free account and register your application to start tracking!</h3>

<%= image_tag("samplegraph.png")%>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-8">
    <ul>
        <li><%= link_to "See your registered applications", registered_applications_show_path %></li>
        <li><%= link_to "Register a new application", registered_applications_new_path %></li>
    </ul>
 </div>
</div>